version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.1
jobs:
  build:
    parameters:
      environment:
        type: string
    docker:
      - image: bnxdev/bnx-firmware-builder
    resource_class: large
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f8:c8:f8:e8:39:17:36:f0:7d:7d:20:18:ac:50:af:98"
      - run: bash .circleci/build.sh << parameters.environment >> $CIRCLE_SHA1
      - run: bash .circleci/package.sh << parameters.environment >> $CIRCLE_SHA1 workspace
      - store_artifacts:
          path: workspace/artifacts
          destination: artifacts
      - persist_to_workspace:
          root: workspace
          paths:
            - '*'
  release_and_deploy:
    parameters:
      environment:
        type: string
      release-option:
        type: string
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/setup
      - run: pip install githubrelease
      - run: bash /tmp/workspace/release.sh << parameters.environment >> $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1 << parameters.release-option >> /tmp/workspace $GITHUB_TOKEN
      - run: bash /tmp/workspace/deploy.sh << parameters.environment >> /tmp/workspace
workflows:
  version: 2
  dev:
    jobs:
      - build:
          name: BuildDev
          environment: dev
          filters:
            branches:
              only:
                - master
      - release_and_deploy:
          name: ReleaseAndDeployDev
          requires:
            - BuildDev
          environment: dev
          release-option: --norelease
          filters:
            branches:
              only:
                - master
  beta:
    jobs:
      - build:
          name: BuildBeta
          environment: beta
          filters:
            branches:
              only:
                - release/beta
      - release_and_deploy:
          name: ReleaseAndDeployBeta
          requires:
            - BuildBeta
          environment: beta
          release-option: --prerelease
          filters:
            branches:
              only:
                - release/beta
  prod:
    jobs:
      - build:
          name: BuildProd
          environment: prod
          filters:
            branches:
              only:
                - release/prod
      - release_and_deploy:
          name: ReleaseAndDeployProd
          requires:
            - BuildProd
          environment: prod
          release-option: ''
          filters:
            branches:
              only:
                - release/prod
